<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for System_Serializer_Dom_Abstract.
 * Generated by PHPUnit on 2009-12-07 at 15:42:42.
 */
class System_Serializer_Dom_AbstractTest extends System_Test_TestCase
{
	
	/**
	 * @var System_Serializer_Dom_Abstract
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = self::getMockForAbstractClass('System_Serializer_Dom_Abstract');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	public function testSetGetOwnerSerializer()
	{
		$this->assertGetterAndSetter($this->object, 'OwnerSerializer', new System_Serializer_Dom());
	}
}
?>
