<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for System_Serializer_Dom_Array.
 * Generated by PHPUnit on 2009-12-07 at 16:00:35.
 */
class System_Serializer_Dom_ArrayTest extends PHPUnit_Framework_TestCase
{
	
	/**
	 * @var System_Serializer_Dom_Array
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new System_Serializer_Dom_Array();
		$this->object->setOwnerSerializer(new  System_Serializer_Dom());
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @todo Implement testSerialize().
	 */
	public function testSerialize()
	{
		$dom = new DOMDocument();
		$dom->appendChild($dom->createElement('xml'));
		
		$this->object->serialize(array('a'=>'b'), $dom->documentElement);
		self::assertXmlStringEqualsXmlString('<xml><a>b</a></xml>', $dom->saveXml());
	}
}
?>
