<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for System_Controller_Action_Helper_GridFilter_Abstract.
 * Generated by PHPUnit on 2009-09-29 at 16:32:58.
 */
class System_Controller_Action_Helper_GridFilter_AbstractTest extends System_Test_TestCase
{
	/**
	 * @var System_Controller_Action_Helper_GridFilter_Abstract
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = $this->getMockForAbstractClass('System_Controller_Action_Helper_GridFilter_Abstract');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		System_Controller_Action_Helper_GridFilter_Abstract::setPluginLoader(null);
	}

	public function testPluginLoader()
	{
		self::assertArrayHasKey('System_Controller_Action_Helper_GridFilter_', $this->object->getPluginLoader()->getPaths());
		$this->assertGetterAndSetter($this->object, 'PluginLoader', new Zend_Loader_PluginLoader(), false);
	}

	public function testFactory()
	{
		$this->object->getPluginLoader()->addPrefixPath('Test', 'Test');
		$class = $this->getMock('System_Controller_Action_Helper_GridFilter_Abstract', array(), array(), 'Test_Test');
		$object = $this->object->factory(array('type'=>'Test'));
		self::assertType('Test_Test', $object);
	}

	/**
	 */
	public function testFilter()
	{
		$class = new System_Controller_Action_Helper_GridFilter_AbstractTest_Filter();
		$class->setFilterData(array('value'=> 'value'));
		$class->setField('field');
		$select = new Zend_Db_Select($this->getMockForAbstractClass('Zend_Db_Adapter_Abstract', array(),  '',  false));
		$class->filter($select);
		self::assertEquals(array("(field = ('value') )"), $select->getPart(Zend_Db_Select::WHERE));
	}
}

class System_Controller_Action_Helper_GridFilter_AbstractTest_Filter extends System_Controller_Action_Helper_GridFilter_Abstract {}
?>
