<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for System_Controller_Action_Helper_GridFilter_Numeric.
 * Generated by PHPUnit on 2009-09-30 at 13:26:43.
 */
class System_Controller_Action_Helper_GridFilter_NumericTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var System_Controller_Action_Helper_GridFilter_Numeric
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new System_Controller_Action_Helper_GridFilter_Numeric;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	public function provider()
	{
		return array(
			array(null, null, '=', 0),
			array(255, 'lt', '<' ,255),
			array('25.3', 'gt', '>', "'25.3'"),
		);
	}
	
	
	
	/**
	 * @dataProvider provider
	 */
	public function testFilterUse($value, $compData, $comp, $rValue)
	{
		$class = $this->object;
		$class->setFilterData(array('value'=> $value, 'comparison'=>$compData));
		$class->setField('field');
		$select = new Zend_Db_Select($this->getMockForAbstractClass('Zend_Db_Adapter_Abstract', array(),  '',  false));
		$class->filter($select);
		self::assertEquals(array("(field ".$comp." (".$rValue.") )"), $select->getPart(Zend_Db_Select::WHERE));
	}
}
?>
