<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for System_Controller_Action_Helper_GridFilter_String.
 * Generated by PHPUnit on 2009-09-30 at 12:15:43.
 */
class System_Controller_Action_Helper_GridFilter_StringTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var System_Controller_Action_Helper_GridFilter_String
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new System_Controller_Action_Helper_GridFilter_String;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}
	
	/**
	 */
	public function testFilter()
	{
		$class = $this->object;
		$class->setFilterData(array('value'=> 'value'));
		$class->setField('field');
		$select = new Zend_Db_Select($this->getMockForAbstractClass('Zend_Db_Adapter_Abstract', array(),  '',  false));
		$class->filter($select);
		self::assertEquals(array("(field like ('%value%') )"), $select->getPart(Zend_Db_Select::WHERE));
	}
}
?>
