<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for System_Serializer_Dom.
 * Generated by PHPUnit on 2009-12-07 at 15:06:57.
 */
class System_Serializer_DomTest extends PHPUnit_Framework_TestCase
{
	
	/**
	 * @var System_Serializer_Dom
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new System_Serializer_Dom;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		System_Serializer_Dom::setPluginLoader(null);
	}

	/**
	 * @todo Implement testSetPluginName().
	 */
	public function testSetPluginName()
	{
		System_Serializer_Dom::setPluginName('123', '123');
		self::assertEquals('123', System_Serializer_Dom::getPluginName('123'));
	}

	/**
	 * @todo Implement testAddPlugin().
	 */
	public function testAddPlugin()
	{
		$this->object->addPlugin('KEY', 'VALUE');
		self::assertArrayHasKey('KEY', $this->object->getPlugins());
		$p = $this->object->getPlugins();
		self::assertEquals('VALUE', $p['KEY']);
	}


	/**
	 * @covers System_Serializer_Dom::getPluginLoader
	 */
	public function testGetPluginLoader() {
		System_Serializer_Dom::setPluginLoader(null);
		self::assertType('Zend_Loader_PluginLoader',System_Serializer_Dom::getPluginLoader());
		self::assertEquals(array('System_Serializer_Dom_' => array('System/Serializer/Dom/')), System_Serializer_Dom::getPluginLoader()->getPaths());
	}

	/**
	 * @covers System_Serializer_Dom::getPluginLoader
	 * @covers System_Serializer_Dom::setPluginLoader
	 */
	public function testSetPluginLoader() {
		$plugin = new Zend_Loader_PluginLoader();
		System_Serializer_Dom::setPluginLoader($plugin);
		self::assertEquals($plugin, System_Serializer_Dom::getPluginLoader());
		System_Serializer_Dom::setPluginLoader(null);
	}

	/**
	 * @todo Implement testGetPlugin().
	 */
	public function testGetPlugin()
	{
		$plugin = $this->object->getPlugin('Form');
		self::assertType('System_Serializer_Dom_Form',$plugin);
		self::assertEquals($this->object, $plugin->getOwnerSerializer());
	}

	/**
	 * @todo Implement testSerialize().
	 */
	public function testSerialize()
	{
		// Remove the following lines when you implement this test.
		$dom = new DOMDocument();
		$dom->appendChild($dom->createElement('xml'));
		$this->object->serialize(array('a'=>'b'), $dom->documentElement);
		self::assertXmlStringEqualsXmlString('<xml><a>b</a></xml>', $dom->saveXml());
	}
}
?>
