<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for System_Application_Resource_Acl.
 * Generated by PHPUnit on 2009-09-22 at 15:09:25.
 */
class System_Application_Resource_AclTest extends System_Test_TestCase 
{
	/**
	 * @var System_Application_Resource_Acl
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new System_Application_Resource_Acl;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	public function testClassLoader() {
		self::assertGetterAndSetter($this->object, 'LoaderClass', 'Options');
	}

	public function testInit() {
		self::assertType('Zend_Acl', $this->object->init());
	}
}
?>
