<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for System_Application_Resource_Auth.
 * Generated by PHPUnit on 2009-09-01 at 17:01:16.
 *
 * @package system.tests
 */
class System_Application_Resource_AuthTest extends PHPUnit_Framework_TestCase 
{
	/**
	 * @var	System_Application_Resource_Auth
	 * @access protected
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 *
	 * @access protected
	 */
	protected function setUp() {
		$this->object = new System_Application_Resource_Auth;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 *
	 * @access protected
	 */
	protected function tearDown() {
	}

	/**
	 *  @covers System_Application_Resource_Auth::init
	 */
	public function testInit() {
		self::assertType('Zend_Auth', $this->object->init());
	}
}
?>
