<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for System_Application_Resource_ResourceAbstract.
 * Generated by PHPUnit on 2009-09-22 at 15:53:37.
 */
class System_Application_Resource_ResourceAbstractTest extends System_Test_TestCase 
{
	/**
	 * @var System_Application_Resource_ResourceAbstract
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = $this->getMockForAbstractClass('System_Application_Resource_ResourceAbstract');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 */
	public function testDependencies() {
		self::assertGetterAndSetter($this->object, 'Dependencies', array());
	}


	/**
	 */
	public function testAddDependency() {
		self::assertEquals(array(), $this->object->getDependencies());
		$this->object->addDependency('dp');
		self::assertEquals(array('dp'), $this->object->getDependencies());
	}

	/**
	 */
	public function testBootstrapDependenciesThrowsException() {
		$this->setExpectedException('Zend_Application_Bootstrap_Exception', 'Resource matching "test" not found');

		$bootstrap = $this->getMock('Zend_Application_Bootstrap_Bootstrap', array('bootstrap'), array(), '', false);
		$this->object->setBootstrap($bootstrap);
		$this->object->addDependency('test');
		$this->object->bootstrapDependencies();
	}
	
	public function testBootstrapDependencies() {
		$bootstrap = $this->getMock('Zend_Application_Bootstrap_Bootstrap', array('_bootstrap'), array(), '', false);
		$bootstrap->expects($this->once())->method('_bootstrap')->will($this->returnValue(null));
		
		$this->object->setBootstrap($bootstrap);
		$this->object->addDependency('db');
		$this->object->bootstrapDependencies();
	}
}

