<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for System_Controller_Action_Json.
 * Generated by PHPUnit on 2009-09-29 at 16:32:58.
 */
class System_Controller_Action_JsonTest extends System_Test_TestCase
{
	public function testConstructor() {
		$requestMock = $this->getMock('Zend_Controller_Request_Abstract');
		$responseMock = $this->getMock('Zend_Controller_Response_Abstract');
		$responseMock->expects($this->once())->method('setHeader')->with('Content-type', 'application/json', true);
		$object = new System_Controller_Action_JsonMock($requestMock, $responseMock);
	}
}

class System_Controller_Action_JsonMock extends System_Controller_Action_Json
{
}

