<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for System_Acl_Loader_Config.
 * Generated by PHPUnit on 2009-09-21 at 18:21:33.
 *
 * @package system.tests
 */
class System_Acl_Loader_ConfigTest extends PHPUnit_Framework_TestCase 
{

	/**
	 * @var System_Acl_Loader_Options
	 */
	protected $object;

	/**
	 * @var Zend_Acl
	 */
	protected $acl;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->acl = new Zend_Acl();
		$this->object = new System_Acl_Loader_Config($this->acl);
	}

	/**
	 * @todo Implement testLoad().
	 */
	public function testLoadNotExistsIniFile() {
		$this->setExpectedException('Zend_Config_Exception');
		$this->object->setOptions(array('config' => 'notExists.ini'));
		$this->object->load();
	}

	/**
	 * @todo Implement testLoad().
	 */
	public function testLoadNotExistsXmlFile() {
		$this->setExpectedException('Zend_Config_Exception');
		$this->object->setOptions(array('config' => 'notExists.xml'));
		$this->object->load();
	}

	/**
	 * @todo Implement testLoad().
	 */
	public function testLoad() {
		$options = array('config' => dirname(__FILE__).'/data/acl.ini');
		$this->object->setOptions($options);
		$this->object->load();
		$options['acl'] = array('allow' => array('guest' => array('default')));
		self::assertEquals($options, $this->object->getOptions());
	}

	/**
	 * @covers System_Acl_Loader_Config::load
	 * @covers System_Acl_Loader_Config::_loadConfig
	 */
	public function testLoadSomeUnknownFormat() {
		$options = array('config' => dirname(__FILE__).'/data/acl.txt');
		$this->object->setOptions($options);

		$this->setExpectedException('Zend_Config_Exception');
		$this->object->load();
	}
}

