<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for System_Form_Element_Checkbox.
 * Generated by PHPUnit on 2009-09-30 at 15:59:56.
 */
class System_Form_Element_CheckboxTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var System_Form_Element_Checkbox
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new System_Form_Element_Checkbox('tets');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @todo Implement testSetValue().
	 */
	public function testSetValueOn()
	{
		$this->object->setValue('on');
		self::assertEquals(1, $this->object->getValue());
		self::assertTrue($this->object->isChecked());
		self::assertEquals($this->object, $this->object->setValue('on'));
		
		$this->object->setValue('1');
		self::assertEquals(1, $this->object->getValue());
		self::assertTrue($this->object->isChecked());
	}
}
?>
