<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for System_Application.
 * Generated by PHPUnit on 2009-09-03 at 12:56:06.
 *
 * @package system.tests
 */
class System_ApplicationTest extends System_Test_TestCase
{
	/**
	 * @var	System_Application
	 * @access protected
	 */
	protected  $application;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 *
	 * @access protected
	 */
	protected function setUp() {
		$this->appliacation = Zend_Registry::get(System_Application::APPLICATION);
		unset(Zend_Registry::getInstance()->{System_Application::APPLICATION});
		$this->configDir = System_Application::getConfigDir();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 *
	 * @access protected
	 */
	protected function tearDown() {
		Zend_Registry::set(System_Application::APPLICATION, $this->appliacation);
		System_Application::setConfigDir($this->configDir);
	}

	/**
	 * @covers System_Application::__construct
	 * @covers System_Application::<protected>
	 */
	public function testConstructor() {
		$app = new System_Application('test');
		self::assertContains('System_',$app->getAutoloader()->getRegisteredNamespaces());
		self::assertTrue(isset(Zend_Registry::getInstance()->{System_Application::APPLICATION}));
	}

	public function testConfigDir() {
		$this->assertGetterAndSetter($this->appliacation, 'ConfigDir', 'test');
	}
	
	

	/**
	 * @covers System_Application::getInstance
	 */
	public function testGetInstanceSetWrong() {
		$this->setExpectedException('Zend_Exception', "No entry is registered for key 'application");
		System_Application::getInstance();
	}

	/**
	 * @covers System_Application::getInstance
	 */
	public function testGetInstanceNotSet() {
		Zend_Registry::set(System_Application::APPLICATION, array());
		$this->setExpectedException('System_Exception', 'Instance not configured');
		System_Application::getInstance();
	}

	/**
	 * @covers System_Application::getInstance
	 */
	public function testGetInstance() {
		$app = new System_Application('test');
		self::assertType('Zend_Application', System_Application::getInstance());
	}

	/**
	 * @covers System_Application::__construct
	 * @covers System_Application::<protected>
	 */
	public function testConstructorWithDir() {
		System_Application::setConfigDir('/data');
		$app = new System_Application('test', dirname(__FILE__));
	}
	/**
	 * @covers System_Application::__construct
	 * @covers System_Application::<protected>
	 */
	public function testConstructorWithDirNoConfigFile() {
		$this->setExpectedException('Zend_Config_Exception');
		$app = new System_Application('test', dirname(__FILE__));
	}

	/**
	 * @covers System_Application::__construct
	 * @covers System_Application::<protected>
	 */
	public function testConstructorWithDirAndCommonFile() {
		$app = new System_Application('test', array('config' => dirname(__FILE__).'/data/application.common.ini'));
	}

}
