<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for Exception.
 * Generated by PHPUnit on 2009-09-15 at 15:47:03.
 *
 * @package system.tests
 */
class ExceptionTest extends PHPUnit_Framework_TestCase 
{
	/**
	 * @covers System_Exception::__construct
	 * @covers System_Exception::__set
	 * @covers System_Exception::__get
	 */
	public function testMagicMethodsSetGet() {
		$e = new System_Exception();
		$this->assertNull($e->lopata);
		$e->lopata = "grabli";
		$this->assertEquals($e->lopata, "grabli");
		try {
			throw $e;
		} catch (System_Exception $e) {
			$this->assertEquals($e->lopata, "grabli");
		}
	}
	
	/**
	 * @covers System_Exception::__construct
	 * @covers System_Exception::__isset
	 * @covers System_Exception::__unset
	 */
	public function testMagicMethodsIssetUnset() {
		$e = new System_Exception();
		self::assertFalse(isset($e->lopata));
		$e->lopata = "grabli";
		self::assertTrue(isset($e->lopata));
		unset($e->lopata);
		self::assertFalse(isset($e->lopata));
	}

	/**
	 * @covers System_Exception::__construct
	 */
	public function testConstructor() {
		$e = new System_Exception('lopata','grabli');
		$this->assertEquals($e->exceptionCode, "grabli");
		try {
			throw $e;
		} catch (System_Exception $e) {
			$this->assertEquals($e->exceptionCode, "grabli");
			$this->assertEquals($e->getMessage(), "lopata");
		}
	}
}
?>
