<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for System_Filter_Db_NameToId.
 * Generated by PHPUnit on 2009-09-29 at 16:32:58.
 */
class System_Filter_Db_NameToIdTest extends System_Test_DatabaseTestCase
{
	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		parent::tearDown();
		System_Locator_TableLocator::unsetInstance();
	}

	public function testConstructorSetTable() {
		$tableMock = $this->getMock('Model_Table_User');
		$field = 'username';
		$obj = new System_Filter_Db_NameToIdMock($tableMock, $field);
		self::assertEquals($tableMock, $obj->getTable());
		self::assertEquals($field, $obj->getField());
	}

	public function testConstructorSetTableName() {
		$tableMock = $this->getMock('Model_Table_User');
		System_Locator_TableLocator::getInstance()->set('User', $tableMock);
		$field = 'username';
		$obj = new System_Filter_Db_NameToIdMock('User', $field);
		self::assertEquals($tableMock, $obj->getTable());
		self::assertEquals($field, $obj->getField());
	}

	public function testFilter() {
		$obj = new System_Filter_Db_NameToId('User', 'username');

		self::assertNull($obj->filter(null));
		self::assertNull($obj->filter('notExistingValue'));
		
		$user = System_Locator_TableLocator::getInstance()->get('User')->find(1)->current();
		self::assertEquals($user->id, $obj->filter($user->username));
	}
}

class System_Filter_Db_NameToIdMock extends System_Filter_Db_NameToId
{
	public function getTable(){
		return $this->_table;
	}

	public function getField() {
		return $this->_field;
	}
}
