<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for System_Controller_Action_Helper_GridFilter.
 * Generated by PHPUnit on 2009-10-05 at 16:22:16.
 */
class System_Controller_Action_Helper_GridFilterTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var System_Controller_Action_Helper_GridFilter
	 */
	protected $object;
	

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		Zend_Controller_Front::getInstance()->setRequest(new Zend_Controller_Request_Simple('a'));
		$this->object = new System_Controller_Action_Helper_GridFilter;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	public function testGetSelect()
	{
		$r = Zend_Controller_Front::getInstance()->getRequest();
		$r->setParam('filter', array(array('field'=>'id','data'=>array('type'=>'numeric'))));
		$r->setParam('sort', 'id');
		
		$table = System_Locator_TableLocator::getInstance()->get('User');
		$select = $this->object->getSelect($table);
		$s = $table->getAdapter()
			->select()
			->from('User', '*')
			->where('id = (0) ')
			->order("id ")
			->limit(25);
		self::assertEquals($s, $select);
	}
	public function testGetSelectDir()
	{
		$r = Zend_Controller_Front::getInstance()->getRequest();
		$r->setParam('sort', 'id');
		$r->setParam('dir', 'ASC');
		
		$table = System_Locator_TableLocator::getInstance()->get('User');
		$select = $this->object->getSelect($table);
		$s = $table->getAdapter()
			->select()
			->from('User', '*')
			->order("id ASC")
			->limit(25);
		self::assertEquals($s, $select);
	}
	

	public function testGetData()
	{
		$data = $this->object->getData(System_Locator_TableLocator::getInstance()->get('User')->select());
		self::assertArrayHasKey('data', $data);
		self::assertArrayHasKey('total', $data);
		self::assertTrue($data['success']);
	}
}
?>
